# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76834a96169508283d4918d742cf7efff8c35abe521dd65b966cff435fa4b419a0595674bfc2c68dfcbe2bf260b4daaf12c7170a3f6144c8b2c756dcfecea1a7

test:
  secret_key_base: 64cba3022becfcf19adddbc16ddda501fea3a0672e4444ee62660e86735dc810f72fabbe696b0d23044dcd3f640aace9ff0e44ac2905bb496e78327edcecb919

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
